// XQuant Phase 3d — paired-vec template instance for XKTQ2_1 K + F16 V.

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE_PAIRED( 64, GGML_TYPE_XKTQ2_1, GGML_TYPE_F16);
DECL_FATTN_VEC_CASE_PAIRED(128, GGML_TYPE_XKTQ2_1, GGML_TYPE_F16);
DECL_FATTN_VEC_CASE_PAIRED(256, GGML_TYPE_XKTQ2_1, GGML_TYPE_F16);
DECL_FATTN_VEC_CASE_PAIRED(512, GGML_TYPE_XKTQ2_1, GGML_TYPE_F16);
