// Dispatch helper for the VTQ_1 family slice of ggml_cuda_flash_attn_ext_vec.
// Covers V=VTQ1_1..VTQ4_1. K may be any supported K type.
//
// Split from fattn-vec-dispatch-vtq.cu so VTQ_1 and VTQ_2 family cases
// compile in parallel (each ~22min instead of combined ~45min).

#include "fattn-vec-dispatch.cuh"

bool try_dispatch_vec_vtq1(ggml_backend_cuda_context & ctx, ggml_tensor * dst) {
    ggml_tensor * Q = dst->src[0];
    ggml_tensor * K = dst->src[1];
    ggml_tensor * V = dst->src[2];

#ifdef GGML_CUDA_FA_ALL_QUANTS
    // V = VTQ1_1
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_F16,   GGML_TYPE_VTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_0,  GGML_TYPE_VTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_1,  GGML_TYPE_VTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q5_0,  GGML_TYPE_VTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q5_1,  GGML_TYPE_VTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q8_0,  GGML_TYPE_VTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_BF16,  GGML_TYPE_VTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_VTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_VTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_VTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_VTQ1_1)

    // V = VTQ2_1
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_F16,   GGML_TYPE_VTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_0,  GGML_TYPE_VTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_1,  GGML_TYPE_VTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q5_0,  GGML_TYPE_VTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q5_1,  GGML_TYPE_VTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q8_0,  GGML_TYPE_VTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_BF16,  GGML_TYPE_VTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_VTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_VTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_VTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_VTQ2_1)

    // V = VTQ3_1
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_F16,   GGML_TYPE_VTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_0,  GGML_TYPE_VTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_1,  GGML_TYPE_VTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q5_0,  GGML_TYPE_VTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q5_1,  GGML_TYPE_VTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q8_0,  GGML_TYPE_VTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_BF16,  GGML_TYPE_VTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_VTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_VTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_VTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_VTQ3_1)

    // V = VTQ4_1
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_F16,   GGML_TYPE_VTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_0,  GGML_TYPE_VTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_1,  GGML_TYPE_VTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q5_0,  GGML_TYPE_VTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q5_1,  GGML_TYPE_VTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q8_0,  GGML_TYPE_VTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_BF16,  GGML_TYPE_VTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_VTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_VTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_VTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_VTQ4_1)
#else
    // Reduced matrix
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_F16,   GGML_TYPE_VTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_F16,   GGML_TYPE_VTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_F16,   GGML_TYPE_VTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_F16,   GGML_TYPE_VTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_0,  GGML_TYPE_VTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_0,  GGML_TYPE_VTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_0,  GGML_TYPE_VTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_0,  GGML_TYPE_VTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q8_0,  GGML_TYPE_VTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q8_0,  GGML_TYPE_VTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q8_0,  GGML_TYPE_VTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q8_0,  GGML_TYPE_VTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_VTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_VTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_VTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_VTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_VTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_VTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_VTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_VTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_VTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_VTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_VTQ4_1)
#endif // GGML_CUDA_FA_ALL_QUANTS

    GGML_UNUSED(ctx); GGML_UNUSED(dst);
    GGML_UNUSED(Q); GGML_UNUSED(K); GGML_UNUSED(V);
    return false;
}
