// Dispatch helper for the KTQ slice of ggml_cuda_flash_attn_ext_vec.
// Covers every case where K or V is a KTQ type (KTQ1_1..KTQ4_1),
// excluding cases where V is a VTQ type — those live in
// fattn-vec-dispatch-vtq.cu.
//
// Split out of fattn.cu to allow parallel cicc instantiation.

#include "fattn-vec-dispatch.cuh"

bool try_dispatch_vec_ktq(ggml_backend_cuda_context & ctx, ggml_tensor * dst) {
    ggml_tensor * Q = dst->src[0];
    ggml_tensor * K = dst->src[1];
    ggml_tensor * V = dst->src[2];

#ifdef GGML_CUDA_FA_ALL_QUANTS
    // V = KTQ1_1
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_F16,   GGML_TYPE_KTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_0,  GGML_TYPE_KTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_1,  GGML_TYPE_KTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q5_0,  GGML_TYPE_KTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q5_1,  GGML_TYPE_KTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q8_0,  GGML_TYPE_KTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_BF16,  GGML_TYPE_KTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_KTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_KTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_KTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_KTQ1_1)

    // V = KTQ2_1
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_F16,   GGML_TYPE_KTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_0,  GGML_TYPE_KTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_1,  GGML_TYPE_KTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q5_0,  GGML_TYPE_KTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q5_1,  GGML_TYPE_KTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q8_0,  GGML_TYPE_KTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_BF16,  GGML_TYPE_KTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_KTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_KTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_KTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_KTQ2_1)

    // V = KTQ3_1
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_F16,   GGML_TYPE_KTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_0,  GGML_TYPE_KTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_1,  GGML_TYPE_KTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q5_0,  GGML_TYPE_KTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q5_1,  GGML_TYPE_KTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q8_0,  GGML_TYPE_KTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_BF16,  GGML_TYPE_KTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_KTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_KTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_KTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_KTQ3_1)

    // V = KTQ4_1
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_F16,   GGML_TYPE_KTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_0,  GGML_TYPE_KTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_1,  GGML_TYPE_KTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q5_0,  GGML_TYPE_KTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q5_1,  GGML_TYPE_KTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q8_0,  GGML_TYPE_KTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_BF16,  GGML_TYPE_KTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_KTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_KTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_KTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_KTQ4_1)

    // K = KTQ, V = standard
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_F16)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_Q4_0)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_Q4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_Q5_0)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_Q5_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_Q8_0)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_BF16)

    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_F16)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_Q4_0)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_Q4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_Q5_0)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_Q5_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_Q8_0)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_BF16)

    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_F16)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_Q4_0)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_Q4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_Q5_0)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_Q5_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_Q8_0)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_BF16)

    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_F16)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_Q4_0)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_Q4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_Q5_0)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_Q5_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_Q8_0)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_BF16)
#else
    // Symmetric K=KTQ=V
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_KTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_KTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_KTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_KTQ4_1)

    // TQ asymmetric: K=TQ, V=f16
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ1_1, GGML_TYPE_F16)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ2_1, GGML_TYPE_F16)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ3_1, GGML_TYPE_F16)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_KTQ4_1, GGML_TYPE_F16)

    // TQ asymmetric: K=standard, V=KTQ (recommended asymmetric configs)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_F16,  GGML_TYPE_KTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_F16,  GGML_TYPE_KTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_F16,  GGML_TYPE_KTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_F16,  GGML_TYPE_KTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_0, GGML_TYPE_KTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_0, GGML_TYPE_KTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_0, GGML_TYPE_KTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q4_0, GGML_TYPE_KTQ4_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q8_0, GGML_TYPE_KTQ1_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q8_0, GGML_TYPE_KTQ2_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q8_0, GGML_TYPE_KTQ3_1)
    FATTN_VEC_CASES_ALL_D_WITH_512_RET(GGML_TYPE_Q8_0, GGML_TYPE_KTQ4_1)
#endif // GGML_CUDA_FA_ALL_QUANTS

    GGML_UNUSED(ctx); GGML_UNUSED(dst);
    GGML_UNUSED(Q); GGML_UNUSED(K); GGML_UNUSED(V);
    return false;
}
