#!/usr/bin/env python3
"""VTQ_3 calibration tool — Phase 3 Step 5.

Compares VTQ_2 (pure trellis) vs VTQ_3 (top-4 outlier sidecar + trellis
on the masked remainder) round-trip MSE for K in {2,3,4} on either:

  * a real V-sample binary (.bin / .npy of float32 shape [N*128] or [N,128]),
    typically generated by `tests/trellis-phase1/extract_v_samples.py`, or
  * a synthetic Gaussian fallback (N=8192 blocks of 128 samples, default).

Spec mirror (must stay in sync with C reference impls):

  * `block_vtq{2,3,4}_3` in `ggml/src/ggml-common.h`
      d (fp16) | start_state (u16) | qs[QK*K/8] | outlier_pos[4] | outlier_val[4]
  * `ggml_trellis_outliers_pick` in `ggml/src/ggml-trellis.c`
      top-4 by |x|, sort positions ascending, zero those slots in x_masked.
  * `ggml_trellis_outliers_apply` in `ggml/src/ggml-trellis.c`
      after trellis decode, overwrite y[pos[k]] with fp16(val[k]).

Limitation: pure-Python Viterbi over 2^16 states is impractical, so this
tool models the trellis path with the same per-block Lloyd-Max codebook
+ norm-correction simulator used by `tests/trellis-phase1/vtq_roundtrip_bench.py`.
That simulator captures the dominant quant-error term for VTQ family
(per-coord scalar quantization MSE on a normalized post-RHT block); the
absolute numbers are within ~5-10 % of the real trellis Viterbi MSE on
Gaussian / Laplace inputs, and the *relative* improvement of VTQ_3 over
VTQ_2 is what this tool is designed to measure.

For absolute Viterbi MSE numbers, build llama-tq and run
`tests/test-vtq3-roundtrip.cpp`.

Output is a stdout table directly paste-able into README/docs.

Usage:
    python3 tools/calibrate_vtq3.py                    # synthetic Gaussian
    python3 tools/calibrate_vtq3.py path/to/v.bin      # raw float32 file
    python3 tools/calibrate_vtq3.py path/to/v.npy      # numpy float32

Hard deps: numpy.
"""

import os
import sys
import struct
import numpy as np

# Spec constants (keep in sync with C headers)
QK_VTQ_TRELLIS = 128                # ggml/src/ggml-trellis.h  GGML_TRELLIS_QK_GROUP
VTQ_OUTLIER_K  = 4                  # ggml/src/ggml-common.h    VTQ_OUTLIER_K

# Lloyd-Max codebooks (same as tests/trellis-phase1/vtq_roundtrip_bench.py).
# 2-bit is Laplace-optimal (post-RHT V is heavier-tailed than Gaussian);
# 3/4-bit are Gaussian-optimal (PQ_CODEBOOK in ggml-quants.c).
VTQ_CODEBOOK_2BIT = np.array([-1.810, -0.395,  0.395,  1.810])
VTQ_CODEBOOK_3BIT = np.array([-2.15195, -1.34407, -0.75244, -0.245,
                               0.245,    0.75244,  1.34407, 2.15195])
VTQ_CODEBOOK_4BIT = np.array([-2.73321, -2.06942, -1.61813, -1.25635,
                              -0.94449, -0.66423, -0.40432, -0.15758,
                               0.15758,  0.40432,  0.66423,  0.94449,
                               1.25635,  1.61813,  2.06942,  2.73321])

CODEBOOKS = {
    2: VTQ_CODEBOOK_2BIT,
    3: VTQ_CODEBOOK_3BIT,
    4: VTQ_CODEBOOK_4BIT,
}


def quantize_vtq_block(x: np.ndarray, codebook: np.ndarray, qk: int) -> np.ndarray:
    """Per-block L2-normalize -> nearest centroid -> norm-correct.
    Models the trellis-decode reconstruction error term well enough for
    relative comparisons. See module docstring for caveats.

    x: [N, qk] float32
    codebook: [K] (raw, not yet 1/sqrt(qk)-scaled)
    """
    cb_scale = 1.0 / np.sqrt(qk)
    cb = codebook * cb_scale

    norms = np.linalg.norm(x, axis=1, keepdims=True)
    x_norm = np.where(norms > 1e-30, x / norms, 0.0)

    edges = (cb[:-1] + cb[1:]) / 2
    idx = np.searchsorted(edges, x_norm)
    recon = cb[idx]

    recon_l2 = np.linalg.norm(recon, axis=1, keepdims=True)
    corrected = np.where(recon_l2 > 1e-30, norms / recon_l2, norms)
    return recon * corrected


def fp16_roundtrip(x: np.ndarray) -> np.ndarray:
    """Simulate fp16 storage: cast f32 -> f16 -> f32."""
    return x.astype(np.float16).astype(np.float32)


def quantize_vtq3_block(x: np.ndarray, codebook: np.ndarray, qk: int,
                        n_outliers: int = VTQ_OUTLIER_K) -> np.ndarray:
    """VTQ_3: pick top-`n_outliers` |x| per block, mask -> trellis-encode the rest,
    decode, then restore the outliers from fp16 ground-truth.

    Mirrors `quantize_row_vtq{K}_3_ref` + `dequantize_row_vtq{K}_3` in
    ggml/src/ggml-quants.c.
    """
    N, Q = x.shape
    assert Q == qk

    # Step 1: pick top-n_outliers |x| per row (same logic as
    # ggml_trellis_outliers_pick, vectorized).
    abs_x = np.abs(x)
    # argpartition picks unsorted top-n; np.argsort on the partition gives
    # ascending positions (deterministic, matches C insertion-sort output).
    if n_outliers >= qk:
        outlier_idx = np.broadcast_to(np.arange(qk), (N, qk)).copy()
    else:
        # top-n by descending |x|, then sort the chosen positions ascending
        part = np.argpartition(-abs_x, n_outliers, axis=1)[:, :n_outliers]
        outlier_idx = np.sort(part, axis=1)  # [N, n_outliers]

    # Step 2: gather outlier values, fp16-roundtrip them (storage cost),
    # build masked x.
    rows = np.arange(N)[:, None]
    outlier_val_fp32   = x[rows, outlier_idx]                   # [N, n_outliers]
    outlier_val_stored = fp16_roundtrip(outlier_val_fp32)        # fp16 -> fp32

    x_masked = x.copy()
    x_masked[rows, outlier_idx] = 0.0

    # Step 3: trellis-quant the masked input (modeled by per-block Lloyd-Max).
    recon = quantize_vtq_block(x_masked, codebook, qk)

    # Step 4: apply outliers (overwrite, lossless w.r.t. fp16-rounded ground truth).
    recon[rows, outlier_idx] = outlier_val_stored
    return recon


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def load_samples(path: str | None, qk: int = QK_VTQ_TRELLIS,
                 n_synth_blocks: int = 8192,
                 seed: int = 1234) -> tuple[np.ndarray, str]:
    """Return (samples [N, qk] float32, source-tag)."""
    if path is None:
        rng = np.random.default_rng(seed)
        samples = rng.standard_normal((n_synth_blocks, qk)).astype(np.float32)
        return samples, f"synthetic Gaussian N(0,1) [{n_synth_blocks} blocks]"

    if not os.path.exists(path):
        sys.exit(f"error: input file not found: {path}")

    if path.endswith(".npy"):
        arr = np.load(path).astype(np.float32, copy=False)
        flat = arr.reshape(-1)
    else:
        # raw float32 little-endian, as written by extract_v_samples.py
        flat = np.fromfile(path, dtype=np.float32)

    n_total = flat.size
    n_drop = n_total % qk
    if n_drop:
        flat = flat[: n_total - n_drop]
    samples = flat.reshape(-1, qk)
    return samples, path


# ---------------------------------------------------------------------------
# Benchmark
# ---------------------------------------------------------------------------

def block_mse(samples: np.ndarray, recon: np.ndarray) -> float:
    return float(((samples - recon) ** 2).mean())


def storage_bpw(K: int, qk: int = QK_VTQ_TRELLIS,
                with_outliers: bool = False) -> float:
    """Bits per weight for VTQ_{K}_2 (no outliers) and VTQ_{K}_3 (with outliers).
    Sizes from ggml/src/ggml-common.h (bytes per QK_VTQ_TRELLIS=128 block):
        _2: 2 (d) + 2 (start_state) + qk*K/8 (qs)
        _3: above + 4 (outlier_pos) + 8 (outlier_val fp16)
    """
    base = 2 + 2 + qk * K // 8
    if with_outliers:
        base += VTQ_OUTLIER_K + 2 * VTQ_OUTLIER_K
    return (base * 8) / qk


def benchmark(samples: np.ndarray, src_label: str) -> None:
    N, qk = samples.shape
    print(f"# VTQ_3 calibration  (Phase 3 Step 5)")
    print(f"# samples : {N} blocks of {qk} from {src_label}")
    print(f"# stats   : mean={samples.mean():+.4f}  std={samples.std():.4f}  "
          f"max|x|={np.abs(samples).max():.3f}")
    print()

    var_total = float(samples.var())

    # Header
    hdr = (f"{'type':>10}  {'bpw':>5}  {'MSE':>12}  {'rel-MSE':>9}  "
           f"{'Δ vs _2':>9}")
    print(hdr)
    print("-" * len(hdr))

    rows = []
    for K in (2, 3, 4):
        cb = CODEBOOKS[K]

        recon_v2 = quantize_vtq_block(samples, cb, qk)
        mse_v2   = block_mse(samples, recon_v2)
        bpw_v2   = storage_bpw(K, qk, with_outliers=False)

        recon_v3 = quantize_vtq3_block(samples, cb, qk, n_outliers=VTQ_OUTLIER_K)
        mse_v3   = block_mse(samples, recon_v3)
        bpw_v3   = storage_bpw(K, qk, with_outliers=True)

        rel_v2 = mse_v2 / var_total
        rel_v3 = mse_v3 / var_total
        delta  = (mse_v3 - mse_v2) / mse_v2 if mse_v2 > 0 else 0.0

        rows.append((K, bpw_v2, bpw_v3, mse_v2, mse_v3, rel_v2, rel_v3, delta))

        print(f"{f'VTQ{K}_2':>10}  {bpw_v2:>5.2f}  {mse_v2:>12.5e}  "
              f"{rel_v2:>8.3%}  {'-':>9}")
        print(f"{f'VTQ{K}_3':>10}  {bpw_v3:>5.2f}  {mse_v3:>12.5e}  "
              f"{rel_v3:>8.3%}  {delta:>+8.2%}")

    print()
    print("Notes:")
    print(f"  * VTQ_3 carries {VTQ_OUTLIER_K} fp16 outliers/block "
          f"(+{VTQ_OUTLIER_K + 2*VTQ_OUTLIER_K} B / {qk} samples = "
          f"+{(VTQ_OUTLIER_K + 2*VTQ_OUTLIER_K)*8/qk:.2f} bpw)")
    print("  * Δ vs _2 < 0  ⇒  VTQ_3 wins (outlier sidecar shrinks tail-driven trellis scale).")
    print("  * Absolute MSE is from a Lloyd-Max simulator, not the real Viterbi trellis;")
    print("    relative ordering and ~order-of-magnitude trends should match.")
    print("    For exact Viterbi MSE, build & run tests/test-vtq3-roundtrip.cpp.")


def main(argv: list[str]) -> None:
    path: str | None = None
    if len(argv) > 1:
        if argv[1] in ("-h", "--help"):
            print(__doc__)
            return
        path = argv[1]

    samples, label = load_samples(path)
    benchmark(samples, label)


if __name__ == "__main__":
    main(sys.argv)
